## Python 102

**Scenario:** Today we are going to build upon the for loops of yesterday. Who has ever got to the cash register at costco, or whole foods, seen the total and asked "how did I spend that much?". Today we have a grocery list of items and prices, but we do not have infinite money (unfortunately), so we need to have a program that will look at our grocery list and help us manage our shopping and cost.

### Learning goals:

Today we will:
 - revisit what for loop does, using a dictionary
 - use `break` to adjust loop activity
 - use nested loops to navigate a nested dictionary
 - write a robust function that will take any nested dictionary of items, costs, and print out your shopping list, stopping when the total cost gets to high, and telling you the average cost per item in your cart.

Let's revisit what a for loop does. Here we have a list of items, and a separate list of costs. We are going to write a loop to print each item, it's cost, and the total of our grocery list.

```
items = ['cheese', 'whole milk', 'kefir', 'tofu four-pack', 'kale', 'oranges', 'ham', 'ben & jerry's']
cost = [2.79, 3.42, 4.50, 12.00, 2.75, 3.64, 25.00, 5.29]
```

![groc-cart](https://images.pexels.com/photos/1389103/pexels-photo-1389103.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260)

### For loops:
First, let's create a for-loop that prints each item in the list with "I need to buy: " item.

In [1]:
items = ['cheese', 'whole milk', 'kefir', 'tofu four-pack', 'kale', 'oranges', 'ham', 'ben & jerry\'s']
cost = [2.79, 3.42, 4.50, 12.00, 2.75, 3.64, 25.00, 5.29]

In [3]:
for item in items:
    print('I need to buy: ' + item + '.')

I need to buy: cheese.
I need to buy: whole milk.
I need to buy: kefir.
I need to buy: tofu four-pack.
I need to buy: kale.
I need to buy: oranges.
I need to buy: ham.
I need to buy: ben & jerry's.


Let's make that a little nicer looking:

```
print("I need to buy: ")
for item in items:
   print(" - [ ] ", item)
```

Okay, we want to work through a dictionary, so what's one way to convert those two lists to a dictionary?

_Hint_: Check [this](https://www.w3schools.com/python/ref_func_zip.asp) documentation. 

In [4]:
print("I need to buy: ")
for item in items:
   print(" - [ ] ", item)

I need to buy: 
 - [ ]  cheese
 - [ ]  whole milk
 - [ ]  kefir
 - [ ]  tofu four-pack
 - [ ]  kale
 - [ ]  oranges
 - [ ]  ham
 - [ ]  ben & jerry's


In [20]:
grocery_list = dict(zip(items, cost))
weird_list = dict(zip(grocery_list, items))
weird_list['cheese'][0]

'c'

So let's now add the total grocery bill at the end:

In [24]:
sum(grocery_list.values())

59.39

Does this look reasonable?

What if you only had $25? 

How can you build it out to stop adding items when the total is over $25?

### While, break, and continue
What does a while loop look like in Python?

In [25]:
i = 1
while i < 6:
  print(i)
  i += 1

1
2
3
4
5


- What is break and continue?
- Are they different? How?
- Run the following code:

In [26]:
i = 0
while i < 6:
  i += 1
  if i == 3:
    print("foo")
    continue
  print(i)

1
2
foo
4
5
6


How does the code above work?

Now run this code:

In [27]:
i = 0
while i < 6:
  i += 1
  if i == 3:
    print("foo")
    break
  print(i)

1
2
foo


Why is the output different?

It stopped at foo, why?

We can also include `breaks` in for-loops.

What would we use to **stop** the for loop if the total reached $25?

In [33]:
sum = 0
for cost in grocery_list.values():
    print(f'{cost}')
    sum += cost
    if sum >= 25:
        print('Too Expensive!')
        break

2.79
3.42
4.5
12.0
2.75
Too Expensive!


What if we wanted to use continue and break to stop the program if an item costs more than **$10** ?

In [ ]:
for cost in grocery_lists.values():
    if cost > 10:
        

### Nested Loops

In [34]:
list2 = [1,2,3,4,5]

for x in list2:
  print('inside loop:', x)
  for y in list2:
    print('outside loop---', y)

inside loop: 1
outside loop--- 1
outside loop--- 2
outside loop--- 3
outside loop--- 4
outside loop--- 5
inside loop: 2
outside loop--- 1
outside loop--- 2
outside loop--- 3
outside loop--- 4
outside loop--- 5
inside loop: 3
outside loop--- 1
outside loop--- 2
outside loop--- 3
outside loop--- 4
outside loop--- 5
inside loop: 4
outside loop--- 1
outside loop--- 2
outside loop--- 3
outside loop--- 4
outside loop--- 5
inside loop: 5
outside loop--- 1
outside loop--- 2
outside loop--- 3
outside loop--- 4
outside loop--- 5


What do you expect to see? Why?

Here's a more complicated example, what is it doing?

In [ ]:
i = 2
while(i < 100):
   j = 2
   while(j <= (i/j)):
      if not(i%j): break
      j = j + 1
   if (j > i/j) : print( i, " is prime")
   i = i + 1

print ("Good bye!")

Here is a more robust shopping list of nested dictionaries:
```
shopping_dict = {'Grocieries': {'ben & jerrys': 5.29, 'cheese': 2.79,'ham': 25.0, 'kale': 2.75,'kefir': 4.5,'oranges': 3.64,'tofu four-pack': 12.0,'whole milk': 3.42},
                 'House supplies': {'toilet paper pack': 16.50, 'clorox spray': 6.43, 'kleenex': 2.50,},
                 'Pet supplies': {'Taste of the Wild': 65.20, 'squeaky toy': 4.50, 'duck feet': 8.45}}
```

write the nested for loops to print out each grocery list with its total

_Hint_

- use [this link](https://pyformat.info/#number) for help in formatting the total to two decimal places

In [35]:
shopping_dict = {'Groceries': {'ben & jerrys': 5.29, 'cheese': 2.79,'ham': 25.0, 'kale': 2.75,'kefir': 4.5,'oranges': 3.64,'tofu four-pack': 12.0,'whole milk': 3.42},
                 'House supplies': {'toilet paper pack': 16.50, 'clorox spray': 6.43, 'kleenex': 2.50,},
                 'Pet supplies': {'Taste of the Wild': 65.20, 'squeaky toy': 4.50, 'duck feet': 8.45}}


In [40]:
for category in shopping_dict.keys():
    print('Total cost is $', sum(shopping_dict[category].values()) + '.')

TypeError: 'float' object is not callable

### Functions

**Built-in functions** <br>
Many useful functions are already built into Python:<br>

`print()`: print the given string or variable's value<br>
`type()`: returns the datatype of the argument<br>
`len()`: returns the length of an array<br>
`sum()`: returns the sum of the array's values<br>
`min()`: returns the smallest member of an array <br>
`max()`: returns the largest member of an array<br>


**Writing your own functions**

```
def sayHello():
  print("Hello!")
```
How do we run it?

```
sayHello()
```

Let's talk about arguments or parameters. Let's say we want to make this function more dynamic and print out whatever we want! How would we do that?
```
def shout(phrase):
  print(phrase + "!!!")
shout("oh hai")
```

What if we don't pass in an argument? What happens?
Maybe we can establish a default value for the argument in case it isn't passed in.

```
def shout(phrase = "oh hai"):
  print(phrase + "!!!")

shout()
shout("bye")
```

What if we wanted to run a function, take its output and put it in to another function?

```
def add_one(number):
  return number + 1

def times_five(number):
  return number * 5

number_plus_one = add_one(1)
answer = times_five(number_plus_one)
print(answer)
```

What will the above code return?

Adapt your shopping list nested for-loop to be wrapped in a function you could call on any shopping list of nested dictionaries.

### Mathematical Notation and Measures of Central Tendency 

median vs mode vs mean<br>
What's the difference?


`samp_list = [1,1,1,1,2,2,2,3,3,10,44]`

How could you write a for loop to calculate the mean?

In [ ]:
samp_list = [1,1,1,1,2,2,2,3,3,10,44]




### Integration

adapt your function to do the following:
- stop the nested loop if a grocery total goes over $30
- print out the average cost of per item in your cart

## Jupyter Bonus

This doesn't really fit in with the rest of Python 102, but Jupyter is incredibly flexible! Here are two examples of embedding beautiful LaTex scripting in a notebook.

In [1]:
%%latex # this will make the entire cell LaTeX syntax
$$\lim\limits_{x \to \infty} \exp(-x) = 0$$

<IPython.core.display.Latex object>

In [2]:
from IPython.display import Math
# this imports a function called Math() in which you can pass in a raw string of LaTeX
Math('F(k) = \int_{-\infty}^{\infty} f(x) e^{2\pi i k} dx')

<IPython.core.display.Math object>